# Generated by Django 5.0.2 on 2024-02-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(max_length=6, verbose_name='Type of car')),
                ('img_1', models.ImageField(upload_to='./sql_imgs')),
                ('img_2', models.ImageField(upload_to='./sql_imgs')),
                ('img_3', models.ImageField(upload_to='./sql_imgs')),
                ('img_4', models.ImageField(upload_to='./sql_imgs')),
                ('img_5', models.ImageField(upload_to='./sql_imgs')),
                ('img_6', models.ImageField(upload_to='./sql_imgs')),
                ('img_7', models.ImageField(upload_to='./sql_imgs')),
                ('img_8', models.ImageField(upload_to='./sql_imgs')),
                ('MSRP', models.CharField(max_length=40, verbose_name='msrp')),
                ('Purchase', models.CharField(max_length=40, verbose_name='purchase')),
                ('rent', models.CharField(max_length=40, verbose_name='rent')),
                ('specs', models.TextField(verbose_name='specs')),
                ('text', models.TextField(verbose_name='About car')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
