# Generated by Django 5.0.2 on 2024-02-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='img_1',
            field=models.ImageField(upload_to='sql_imgs/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='img_2',
            field=models.ImageField(upload_to='sql_imgs/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='img_3',
            field=models.ImageField(upload_to='sql_imgs/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='img_4',
            field=models.ImageField(upload_to='sql_imgs/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='img_5',
            field=models.ImageField(upload_to='sql_imgs/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='img_6',
            field=models.ImageField(upload_to='sql_imgs/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='img_7',
            field=models.ImageField(upload_to='sql_imgs/'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='img_8',
            field=models.ImageField(upload_to='sql_imgs/'),
        ),
    ]
